"""
Full-length PSSM reconstruction processing module.

This module implements Branch B full-length PSSM reconstruction:

- Load original full-length protein sequences
- Load selected CD-Search domain alignment table
- Load domain-level PSSM matrices generated by smp_parse
- Project domain-level PSSM values back to full-length coordinates
- Export one reconstructed PSSM table per query sequence

The output structure and file names are designed to remain compatible
with the original PSSM/src/preprocess/run_pssm_reconstruct.py implementation.
"""

from __future__ import annotations

# Standard Library Imports
import time
from pathlib import Path
from typing import Dict

# Third-Party Imports
import pandas as pd
from Bio import SeqIO

AA_ORDER = list("GAILVMFWPCSTYNQHKRDE")


def load_alignment_table(path: Path) -> pd.DataFrame:
    """
    Load selected CD-Search domain alignment table.
    """
    if not path.exists():
        raise FileNotFoundError(f"Selected CD-Search domain table not found: {path}")

    return pd.read_csv(path, sep="\t")


def load_original_sequences(fasta_path: Path) -> Dict[str, str]:
    """
    Load original full-length protein sequences from FASTA.

    Returns
    -------
    dict
        Mapping from sequence ID to sequence string.
    """
    if not fasta_path.exists():
        raise FileNotFoundError(f"Input FASTA not found: {fasta_path}")

    return {rec.id: str(rec.seq) for rec in SeqIO.parse(str(fasta_path), "fasta")}


def load_domain_pssm_matrix(
    *,
    matrix_dir: Path,
    query_id: str,
    pssm_id: int,
) -> pd.DataFrame:
    """
    Load domain-level PSSM matrix.

    Expected file naming convention:
        {query_id}_{pssm_id}_hseq_with_gap.tsv

    Example:
        P00001_231391_hseq_with_gap.tsv
    """
    file_name = f"{query_id}_{pssm_id}_hseq_with_gap.tsv"
    file_path = matrix_dir / file_name

    if not file_path.exists():
        raise FileNotFoundError(f"PSSM matrix not found: {file_path}")

    return pd.read_csv(file_path, sep="\t")


def reconstruct_full_pssm(
    *,
    original_seq: str,
    aln_row: pd.Series,
    domain_pssm: pd.DataFrame,
    aa_order: str = "GAILVMFWPCSTYNQHKRDE",
) -> pd.DataFrame:
    """
    Reconstruct full-length PSSM matrix using CD-Search alignment mapping.

    Rules
    -----
    - Only aligned residues receive PSSM values.
    - Unaligned positions remain NaN.
    - Output uses full-length protein coordinate system: 1..L.
    """
    aa_order_list = list(aa_order)
    length = len(original_seq)

    columns = (
        ["Position", "Residue", "Alignment"]
        + aa_order_list
        + ["Po", "Hy", "Ch", "|Hy-Ch|", "|Hy-Po|"]
    )

    out = pd.DataFrame(index=range(1, length + 1), columns=columns)

    out["Position"] = range(1, length + 1)
    out["Residue"] = list(original_seq)
    out["Alignment"] = "0 (unaligned)"

    qseq = aln_row["qseq"]
    hseq = aln_row["hseq"]

    orig_pos = int(aln_row["qstart"])
    pssm_row_index = 0

    feature_columns = aa_order_list + ["Po", "Hy", "Ch", "|Hy-Ch|", "|Hy-Po|"]

    for q_char, h_char in zip(qseq, hseq):
        q_gap = q_char == "-"
        h_gap = h_char == "-"

        if not q_gap and not h_gap:
            if pssm_row_index < len(domain_pssm):
                row = domain_pssm.iloc[pssm_row_index]

                values = row[feature_columns].values
                out.loc[orig_pos, columns[3:]] = values
                out.loc[orig_pos, "Alignment"] = "1 (aligned)"

            pssm_row_index += 1
            orig_pos += 1

        elif not q_gap and h_gap:
            orig_pos += 1

        elif q_gap and not h_gap:
            pssm_row_index += 1

    return out


def run_pssm_reconstruct(
    *,
    query_fasta: Path,
    cdsearch_table: Path,
    matrix_dir: Path,
    output_dir: Path,
    aa_order: str = "GAILVMFWPCSTYNQHKRDE",
    resume: bool = True,
) -> None:
    """
    Reconstruct full-length PSSM matrices using alignment projection.

    Parameters
    ----------
    query_fasta : pathlib.Path
        Original full-length protein FASTA.
    cdsearch_table : pathlib.Path
        Selected CD-Search domain table generated by cdsearch_extract.
    matrix_dir : pathlib.Path
        Directory containing domain-level matrix TSV files.
    output_dir : pathlib.Path
        Directory to write reconstructed full-length PSSM TSV files.
    aa_order : str, optional
        Amino-acid column order.
    resume : bool, optional
        If True, skip reconstructed files that already exist.

    Returns
    -------
    None
    """
    start_time = time.time()

    print("\n╔══════════════════════════════════════════════════════════════════════╗")
    print("║              [ Full-length PSSM Reconstruction Stage Started ]       ║")
    print("╚══════════════════════════════════════════════════════════════════════╝\n")

    output_dir.mkdir(parents=True, exist_ok=True)

    log_path = output_dir / "pssm_reconstruct_error.log"

    print(f"📂 PSSM Matrix Dir     : {matrix_dir}")
    print(f"📁 Reconstruct Out Dir : {output_dir}")
    print(f"🐛 Error Log           : {log_path}")
    print(f"📂 FASTA Path          : {query_fasta}")
    print(f"📄 Selected Domain Table: {cdsearch_table}\n")

    aln_table = load_alignment_table(cdsearch_table)
    original_seqs = load_original_sequences(query_fasta)

    total = len(aln_table)
    success = 0
    skipped = 0
    failed = 0

    for idx, row in aln_table.iterrows():
        query_id = row["query_id"]
        pssm_id = int(row["PSSM_ID"])

        progress = (idx + 1) / total * 100
        out_path = output_dir / f"{query_id}.tsv"

        print("─" * 70)
        print(
            f"▶️  [{idx + 1:3d}/{total:<3d} | {progress:5.1f}% ] "
            f"{query_id} (PSSM {pssm_id})"
        )
        print("─" * 70)

        if resume and out_path.exists():
            skipped += 1
            print(f"   ⏩ Skip (already reconstructed): {out_path.name}\n")
            continue

        try:
            if query_id not in original_seqs:
                raise KeyError(f"Query sequence not found in FASTA: {query_id}")

            domain_pssm = load_domain_pssm_matrix(
                matrix_dir=matrix_dir,
                query_id=query_id,
                pssm_id=pssm_id,
            )

            original_seq = original_seqs[query_id]

            full_pssm = reconstruct_full_pssm(
                original_seq=original_seq,
                aln_row=row,
                domain_pssm=domain_pssm,
                aa_order=aa_order,
            )

            full_pssm.to_csv(out_path, sep="\t", index=False)

            success += 1
            print(f"   ✅ Reconstructed successfully for {query_id}\n")

        except Exception as exc:  # pylint: disable=broad-exception-caught
            failed += 1
            print(f"   ❌ Reconstruction failed for {query_id}: {exc}\n")

            with log_path.open("a", encoding="utf-8") as log:
                log.write(f"[{query_id}] {exc}\n")

    elapsed = time.time() - start_time

    print("\n" + "╔" + "═" * 70 + "╗")
    print("║" + " " * 22 + "PSSM Reconstruction Summary" + " " * 20 + "║")
    print("╚" + "═" * 70 + "╝\n")

    print("📊 Summary Statistics")
    print("─" * 70)
    print(f"Total proteins : {total}")
    print(f"Successful     : {success}")
    print(f"Skipped        : {skipped}")
    print(f"Failed         : {failed}")
    print(f"🐛 Error log   : {log_path}")
    print(f"⏱️  Elapsed    : {elapsed:.2f} seconds\n")

    print("✅  Full-length PSSM reconstruction stage completed!\n")
