"""
CD-Search pipeline orchestration module.

This module validates configuration sections, checks required input
resources, prepares output directories, and dispatches the actual
RPS-BLAST/CD-Search processing logic.

The CD-Search stage generates search and selection artifacts only:

- CD-Search all-hits table
- Query-to-PSSM candidate table
- Default top1 PSSM proposal table
- Metadata table

Alignment blocks and domain FASTA files are intentionally generated by
a separate extraction stage after the selected PSSM table is confirmed.

The actual sequence-level RPS-BLAST execution and XML parsing logic
is implemented in:

    search.processing.cdsearch
"""

from __future__ import annotations

# Standard Library Imports
import shutil
from pathlib import Path
from typing import Any, Dict

# App Imports
from search.exceptions import PipelineError
from search.utils.fs_utils import remove_directory_tree

PIPELINE_NAME = "cdsearch"


def run_cdsearch_pipeline(
    *,
    inputs: Dict[str, Any],
    parameters: Dict[str, Any],
    outputs: Dict[str, Any],
    execution: Dict[str, Any],
) -> None:
    """
    Run the CD-Search pipeline.

    This function is the pipeline-level entry point called by:

        search run --pipeline cdsearch --config configs/stages/cdsearch.yaml

    This stage performs local RPS-BLAST against the CDD database and writes
    CD-Search result artifacts. It does not extract selected domain FASTA
    files directly.

    Parameters
    ----------
    inputs : dict
        Input paths and external resources.

        Expected keys:
        - query_fasta
        - cdd_rpsblast_db

    parameters : dict
        Tool parameters that affect scientific results.

        Expected keys:
        - evalue
        - outfmt
        - num_threads

    outputs : dict
        Output locations.

        Expected keys:
        - cdsearch_root

    execution : dict
        Execution behavior.

        Expected keys:
        - overwrite
        - resume

    Returns
    -------
    None
    """
    config = _normalize_cdsearch_config(
        inputs=inputs,
        parameters=parameters,
        outputs=outputs,
        execution=execution,
    )

    _validate_cdsearch_resources(config)
    _prepare_cdsearch_output_dir(config)
    _print_cdsearch_configuration(config)

    # Import here to keep CLI startup lightweight and to avoid importing
    # Biopython/pandas until the pipeline is actually executed.
    from search.processing.cdsearch import (
        run_cdsearch,  # pylint: disable=import-outside-toplevel
    )

    run_cdsearch(
        query_fasta=config["query_fasta"],
        cdd_rpsblast_db=config["cdd_rpsblast_db"],
        output_dir=config["cdsearch_root"],
        evalue=config["evalue"],
        outfmt=config["outfmt"],
        num_threads=config["num_threads"],
        resume=config["resume"],
    )


def _normalize_cdsearch_config(
    *,
    inputs: Dict[str, Any],
    parameters: Dict[str, Any],
    outputs: Dict[str, Any],
    execution: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Normalize CD-Search configuration sections into a flat dictionary.

    This function also applies default values that match the original
    run_cdsearch.py behavior.
    """
    required_inputs = ["query_fasta", "cdd_rpsblast_db"]
    required_outputs = ["cdsearch_root"]

    for key in required_inputs:
        if key not in inputs or inputs[key] in (None, ""):
            raise PipelineError(
                pipeline=PIPELINE_NAME,
                stage="validate_config",
                reason=f"Missing required input field: inputs.{key}",
                action=(
                    "Add the missing field to configs/stages/cdsearch.yaml "
                    "under the 'inputs' section."
                ),
                context={
                    "missing_key": f"inputs.{key}",
                },
            )

    for key in required_outputs:
        if key not in outputs or outputs[key] in (None, ""):
            raise PipelineError(
                pipeline=PIPELINE_NAME,
                stage="validate_config",
                reason=f"Missing required output field: outputs.{key}",
                action=(
                    "Add the missing field to configs/stages/cdsearch.yaml "
                    "under the 'outputs' section."
                ),
                context={
                    "missing_key": f"outputs.{key}",
                },
            )

    config = {
        # Inputs
        "query_fasta": Path(inputs["query_fasta"]),
        "cdd_rpsblast_db": Path(inputs["cdd_rpsblast_db"]),
        # Parameters
        # Defaults follow the original implementation:
        #   rpsblast -outfmt 5 -evalue 0.001 -num_threads 8
        "evalue": parameters.get("evalue", 0.001),
        "outfmt": parameters.get("outfmt", 5),
        "num_threads": parameters.get("num_threads", 8),
        # Outputs
        "cdsearch_root": Path(outputs["cdsearch_root"]),
        # Execution behavior
        "overwrite": bool(execution.get("overwrite", False)),
        "resume": bool(execution.get("resume", True)),
    }

    _validate_cdsearch_parameters(config)

    return config


def _validate_cdsearch_parameters(config: Dict[str, Any]) -> None:
    """
    Validate CD-Search parameter values.
    """
    try:
        config["evalue"] = float(config["evalue"])
    except (TypeError, ValueError) as exc:
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_parameters",
            reason="Invalid evalue parameter.",
            action="Set parameters.evalue to a numeric value, for example 0.001.",
            context={
                "evalue": config.get("evalue"),
            },
        ) from exc

    if config["evalue"] <= 0:
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_parameters",
            reason="evalue must be greater than 0.",
            action="Set parameters.evalue to a positive numeric value.",
            context={
                "evalue": config["evalue"],
            },
        )

    try:
        config["outfmt"] = int(config["outfmt"])
    except (TypeError, ValueError) as exc:
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_parameters",
            reason="Invalid outfmt parameter.",
            action="Set parameters.outfmt to an integer value. Use 5 for XML output.",
            context={
                "outfmt": config.get("outfmt"),
            },
        ) from exc

    if config["outfmt"] != 5:
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_parameters",
            reason="Unsupported RPS-BLAST output format for this pipeline.",
            action=(
                "Set parameters.outfmt to 5. The current parser uses "
                "Bio.Blast.NCBIXML and therefore requires BLAST XML output."
            ),
            context={
                "outfmt": config["outfmt"],
            },
        )

    try:
        config["num_threads"] = int(config["num_threads"])
    except (TypeError, ValueError) as exc:
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_parameters",
            reason="Invalid num_threads parameter.",
            action="Set parameters.num_threads to a positive integer.",
            context={
                "num_threads": config.get("num_threads"),
            },
        ) from exc

    if config["num_threads"] < 1:
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_parameters",
            reason="num_threads must be greater than or equal to 1.",
            action="Set parameters.num_threads to a positive integer.",
            context={
                "num_threads": config["num_threads"],
            },
        )


def _validate_cdsearch_resources(config: Dict[str, Any]) -> None:
    """
    Validate input FASTA, CDD RPS-BLAST database, and external command.
    """
    query_fasta = config["query_fasta"]
    cdd_rpsblast_db = config["cdd_rpsblast_db"]

    if not query_fasta.is_file():
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_inputs",
            reason="Input FASTA file does not exist.",
            action="Check inputs.query_fasta in configs/stages/cdsearch.yaml.",
            context={
                "query_fasta": str(query_fasta),
            },
        )

    if not _has_rpsblast_database_files(cdd_rpsblast_db):
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_inputs",
            reason="CDD RPS-BLAST database files were not found.",
            action=(
                "Check inputs.cdd_rpsblast_db in configs/stages/cdsearch.yaml. "
                "It should point to the database basename, for example: "
                "data/external/cdd/rpsblast/Cdd. "
                "If the database has not been built, run the CDD setup script first."
            ),
            context={
                "cdd_rpsblast_db": str(cdd_rpsblast_db),
                "expected_files": f"{cdd_rpsblast_db}.*",
            },
        )

    if shutil.which("rpsblast") is None:
        raise PipelineError(
            pipeline=PIPELINE_NAME,
            stage="validate_environment",
            reason="rpsblast command was not found in PATH.",
            action=(
                "Activate the correct conda environment first, for example: "
                "'conda activate search'. If BLAST+ is not installed, install it "
                "with: 'conda install -c bioconda blast'."
            ),
            context={
                "command": "rpsblast",
            },
        )


def _has_rpsblast_database_files(db_basename: Path) -> bool:
    """
    Check whether RPS-BLAST database files exist for a database basename.

    Example
    -------
    If db_basename is:

        data/external/cdd/rpsblast/Cdd

    this function checks whether files like the following exist:

        data/external/cdd/rpsblast/Cdd.*
    """
    matched_files = list(db_basename.parent.glob(f"{db_basename.name}.*"))
    return len(matched_files) > 0


def _prepare_cdsearch_output_dir(config: Dict[str, Any]) -> None:
    """
    Prepare the CD-Search output directory according to execution settings.

    If overwrite is true, the existing output directory is removed and the
    CD-Search stage is rebuilt from scratch.

    If overwrite is false and resume is true, existing XML files under the
    intermediate directory can be reused by the processing layer.

    If overwrite is false and resume is false, this function refuses to write
    into a non-empty output directory to avoid mixing old and new artifacts.
    """
    output_dir = config["cdsearch_root"]
    overwrite = config["overwrite"]
    resume = config["resume"]

    if output_dir.exists():
        if overwrite:
            remove_directory_tree(str(output_dir), include_self=True)
            output_dir.mkdir(parents=True, exist_ok=True)
            return

        if not resume and any(output_dir.iterdir()):
            raise PipelineError(
                pipeline=PIPELINE_NAME,
                stage="prepare_outputs",
                reason="Output directory already exists and is not empty.",
                action=(
                    "Either set execution.overwrite: true to rebuild from scratch, "
                    "or set execution.resume: true to continue from existing XML files."
                ),
                context={
                    "output_dir": str(output_dir),
                    "overwrite": overwrite,
                    "resume": resume,
                },
            )

        output_dir.mkdir(parents=True, exist_ok=True)
        return

    output_dir.mkdir(parents=True, exist_ok=True)


def _print_cdsearch_configuration(config: Dict[str, Any]) -> None:
    """
    Print a simple CD-Search configuration summary.
    """
    print()
    print("[CD-Search Configuration]")
    print(f"Input FASTA      : {config['query_fasta']}")
    print(f"CDD database     : {config['cdd_rpsblast_db']}")
    print(f"Output directory : {config['cdsearch_root']}")
    print()
    print("[Parameters]")
    print(f"evalue           : {config['evalue']}")
    print(f"outfmt           : {config['outfmt']}")
    print(f"num_threads      : {config['num_threads']}")
    print()
    print("[Execution]")
    print(f"overwrite        : {config['overwrite']}")
    print(f"resume           : {config['resume']}")
    print()
    print("[Expected Outputs]")
    print(
        "all hits         : "
        f"{config['cdsearch_root'] / 'cdsearch_all_hits_detailed.tsv'}"
    )
    print(
        "candidate table  : "
        f"{config['cdsearch_root'] / 'cdsearch_query_pssm_candidates.tsv'}"
    )
    print(
        "default top1     : " f"{config['cdsearch_root'] / 'cdsearch_default_top1.tsv'}"
    )
    print("metadata         : " f"{config['cdsearch_root'] / 'cdsearch_metadata.tsv'}")
    print()
